# Generated by Django 4.0 on 2023-11-04 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Costom_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_soobsh', models.CharField(max_length=100)),
                ('inn', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('pint_head', models.CharField(max_length=100)),
                ('name_head', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('web', models.CharField(max_length=100)),
                ('settlement', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('ur_address', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('fact_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurse.costom_user')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='nurse.costom_user')),
            ],
        ),
    ]
