# Generated by Django 4.0 on 2023-11-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('name_purchase', models.CharField(max_length=100)),
                ('method', models.CharField(max_length=100)),
                ('planned_sum', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('deadline', models.CharField(max_length=100)),
                ('chatgpt', models.TextField()),
            ],
        ),
    ]
